### ISSUE TITLE
Write a constexpr find for array of C strings

### ISSUE THREAD

**Issue by rep-movsd** [rep-movsd/see-phit#8]
For tag name validation, we would need to check if the given string exists in the long array of tags.

Either use a binary tree or a hashing approach and write a constexpr function to detect a matching tags index in the tag array

**Comment by agauniyal** [comment]
binary tree not possible as of now, same issue of dynamic allocation would obstruct creation of new nodes. We could use heap structured binary tree (using constexpr array) but don't know how that will fair with its limits. Compile time hash was current year's google gsoc proposal under Boost Library :p
